#!/usr/bin/env bash

echo 'pre commit hook'

echo 'check tslint'
node node_modules/tslint/bin/tslint src/*.ts || exit 1
echo 'tslint =>> ok'

echo 'run tests'
npm run minify_test || exit 1
echo 'test =>> ok'

exit 0
