#!/usr/bin/env bash

echo 'check tslint'
node node_modules/tslint/bin/tslint src/*.ts || exit 1
echo 'tslint src/*.ts =>> ok'

echo 'tslint test/*.ts =>> ok'
node node_modules/tslint/bin/tslint test/*.ts || exit 1
echo 'tslint =>> ok'
